reset;

model ./kktreformulation1.mod;
data ./instances1/notPSD_random8.dat;

#option solver couenne;
#option baron_options "prfreq=10 outlev=1 maxtime = -1";
option solver gurobi;
option gurobi_options "NonConvex=2 timelim=18000 outlev=1";

solve;
display Q,q,c,LSE, _total_solve_time;
printf('Average square error reconstruction: ');
print LSE/p_max;
display y, lambda1, lambda2;
display stationarity,complementary1,complementary2,nonnegativity;

